apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "layer1_port_cdstar.fullname" . }}
  labels:
{{ include "layer1_port_cdstar.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "layer1_port_cdstar.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "layer1_port_cdstar.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "cdstar_PUBLICKEY"
            valueFrom:
              secretKeyRef:
                name: cdstar-keys
                key: publicKey.pem
          - name: "cdstar_PRIVATEKEY"
            valueFrom:
              secretKeyRef:
                name: cdstar-keys
                key: privateKey.pem
          envFrom:
          - configMapRef:
            name: mservice
          - configMapRef:
            name: proxy
          - configMapRef:
            name: globalenvvar
          - configMapRef:
            name: portcdstarconfig
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
