import logging
import os
import json
import requests
from RDS import Util
from flask import jsonify, request, g, abort
from io import BytesIO, BufferedReader

logger = logging.getLogger()


def index(project_id):
    abort(500)


def get(project_id, file_id):
    abort(500)


def post(project_id):
    # TODO: If jwt will be generated by Sciebo RDS through certificates, then you need passive mode for FileTransferMode and can create here everything you need, because only this endpoint will be called.
    # Otherwise you need all endpoints, but this would be the ideomatic way to implement for sciebo RDS.
    # Look at port-datasafe (https://github.com/Sciebo-RDS/port_datasafe/blob/24043d71bfd79a0dd3ca5ade32597b4e1fe45bf1/src/api/project/files.py#L22) for example for jwt workflow.
    abort(500)


def patch(project_id, file_id):
    abort(500)


def delete(project_id, file_id=None):
    abort(500)
